version: '3.8'
services:
  video-understanding:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility